language: node_js
node_js:
- '10'
deploy:
  provider: npm
  email: tamed.lionheart@gmail.com
  api_key:
    secure: svIinBou/+iqFDQ0MbNTN5ABGSaw20gVnBTlJ1tNkIcY/N5nKMoEKbriaiRYn2iDpU5REsoDWx9KAC95vex16dmFLvwb2j5zzU6h+LfOvXJyH/itw9SBrlENP4ZBPsOFuLZSu/Slrolhq9pjYgXUEpPqW7Sahvo2Wh1Hb8ic3oRpcPrvotWSLaseispnOG5GDO1fNACB9JBDVegkgqxuJpUyb6paHJ2+srS7GSqkY43YhAj6Ir10Pfi1BJSsc1YHYak0C48x99IW3YRlG5/sZiFc/7dsuXK+rajSRwWOeGiCAsA4NXDeuyEBfzMA39JQgFUlX5QSz13U0odouDiM68k5PLLoGESBY7O0Hioq8S39bZkyLE2TKQbTqzmnTNztK1n158/hGFPgNevzfRrXutmt6fZ5vdcWUc/i5p+8KNaXyN8CuZtcKLk3RcEV6DRwspZrl3aTZhjQEdZi/5tN7sbZU9kwcOmFAOk/JWoBM1nP03evysol8/73wLNPD0WtWcK4j24gJYivC+/vhmRaHheRX428+xp+WK+8fStMwIgw5dVqFbgrtXlJcDdCF54OiX6uB1p7YtFnu8/z9w542nOQeiBhVp93GCVxF3vajCLtpXm9lQMMEnqaDJ/pB3HPoVvBhotW09/fHpWoeOKJoOFDy/kjNDvUn8ND9GK+d9c=
  on:
    branch: master
    tags: true
    repo: jnmorse/eslint-config-jnmorse
